name: Build & Release App
on:
  workflow_dispatch: 

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Build App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "Gmach Tools v__VERSION__"
          releaseBody: "גרסה יציבה ואופטימלית של גמ\"ח כלי עבודה."
          releaseDraft: false
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gmach-Tools-Installers
          path: src-tauri/target/release/bundle/msi/*.msi
